// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: usuario.
// - Entity ID: 102019b932a38be7e57a16f552ac3ec2fb2.
// - Entity Version: 102019bce3bf5b07679974e1d0aa86f47f5.
// - Task ID: 696c1755bcaec6128e359044.
// - Task Root ID: 695cef7bc0662b03161297fc.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for UsuarioPerfil
 */
export enum UsuarioPerfil {
  Unspecified = 0,
  Locador = 1,
  Locatario = 2,
  Admin = 3,
}



/**
 * Interface for UsuarioModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface UsuarioModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  cpf_cnpj: string;
  email: string;
  wallet_address?: string | null;
  perfil: UsuarioPerfil;
}

/**
 * ORM class for Usuario entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class UsuarioORM {
  private static instance: UsuarioORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b932a38be7e57a16f552ac3ec2fb2';
    this.entityName = 'usuario';
    this.entityVersion = '102019bce3bf5b07679974e1d0aa86f47f5';
    this.taskId = '696c1755bcaec6128e359044';
    this.taskRootId = '695cef7bc0662b03161297fc';
  }

  /**
   * Get singleton instance of UsuarioORM
   */
  public static getInstance(): UsuarioORM {
    if (!UsuarioORM.instance) {
      UsuarioORM.instance = new UsuarioORM();
    }
    
    return UsuarioORM.instance;
  }

  /**
   * Get usuario by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getUsuarioByIDs(ids: string[]): Promise<UsuarioModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete usuario by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteUsuarioByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Usuario records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllUsuario(): Promise<UsuarioModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Usuario record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertUsuario(data: UsuarioModel[]): Promise<UsuarioModel[]> {
    const structured = data.map((item) => CreateData(UsuarioModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Usuario records
   */
  async purgeAllUsuario(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Usuario records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listUsuario(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[UsuarioModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get usuario by Id index
   * This function gets data by index.
   */
  async getUsuarioById(
    id: string,
  ): Promise<UsuarioModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) usuario by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUsuarioById(
    id: string,
    data: UsuarioModel
  ): Promise<UsuarioModel[]> {
    const index = createIndexId(
      id
    );

    const values = UsuarioModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete usuario by Id index
   */
  async deleteUsuarioById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get usuario by Email index
   * This function gets data by index.
   */
  async getUsuarioByEmail(
    email: string,
  ): Promise<UsuarioModel[]> {
    const index = createIndexEmail(
      email
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) usuario by Email index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUsuarioByEmail(
    email: string,
    data: UsuarioModel
  ): Promise<UsuarioModel[]> {
    const index = createIndexEmail(
      email
    );

    const values = UsuarioModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete usuario by Email index
   */
  async deleteUsuarioByEmail(
    email: string
  ): Promise<void> {
    const index = createIndexEmail(
      email
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get usuario by CpfCnpj index
   * This function gets data by index.
   */
  async getUsuarioByCpfCnpj(
    cpf_cnpj: string,
  ): Promise<UsuarioModel[]> {
    const index = createIndexCpfCnpj(
      cpf_cnpj
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) usuario by CpfCnpj index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUsuarioByCpfCnpj(
    cpf_cnpj: string,
    data: UsuarioModel
  ): Promise<UsuarioModel[]> {
    const index = createIndexCpfCnpj(
      cpf_cnpj
    );

    const values = UsuarioModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete usuario by CpfCnpj index
   */
  async deleteUsuarioByCpfCnpj(
    cpf_cnpj: string
  ): Promise<void> {
    const index = createIndexCpfCnpj(
      cpf_cnpj
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get usuario by WalletAddress index
   * This function gets data by index.
   */
  async getUsuarioByWalletAddress(
    wallet_address: string,
  ): Promise<UsuarioModel[]> {
    const index = createIndexWalletAddress(
      wallet_address
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) usuario by WalletAddress index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUsuarioByWalletAddress(
    wallet_address: string,
    data: UsuarioModel
  ): Promise<UsuarioModel[]> {
    const index = createIndexWalletAddress(
      wallet_address
    );

    const values = UsuarioModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete usuario by WalletAddress index
   */
  async deleteUsuarioByWalletAddress(
    wallet_address: string
  ): Promise<void> {
    const index = createIndexWalletAddress(
      wallet_address
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get usuario by DataCreator index
   * This function gets data by index.
   */
  async getUsuarioByDataCreator(
    data_creator: string,
  ): Promise<UsuarioModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) usuario by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUsuarioByDataCreator(
    data_creator: string,
    data: UsuarioModel
  ): Promise<UsuarioModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = UsuarioModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete usuario by DataCreator index
   */
  async deleteUsuarioByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get usuario by DataUpdater index
   * This function gets data by index.
   */
  async getUsuarioByDataUpdater(
    data_updater: string,
  ): Promise<UsuarioModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) usuario by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUsuarioByDataUpdater(
    data_updater: string,
    data: UsuarioModel
  ): Promise<UsuarioModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = UsuarioModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete usuario by DataUpdater index
   */
  async deleteUsuarioByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to UsuarioModel data array
   */
  private resultToData(values: Data[]): UsuarioModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return UsuarioModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as UsuarioModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized UsuarioModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is UsuarioModel => item !== null);
  }
}

/**
 * Convert UsuarioModel data to Value array
 */
function UsuarioModelToValues(data: UsuarioModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'cpf_cnpj', type: DataType.string, defaultValue: '' },
    { key: 'email', type: DataType.string, defaultValue: '' },
    { key: 'wallet_address', type: DataType.string, defaultValue: null },
    { key: 'perfil', type: DataType.enumeration, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof UsuarioModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to UsuarioModel data
 */
function UsuarioModelFromValues(values: Value[]): UsuarioModel {
  const data: Partial<UsuarioModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'cpf_cnpj':
        data.cpf_cnpj = ParseValue(value, DataType.string) as string;
        break;
      case 'email':
        data.email = ParseValue(value, DataType.string) as string;
        break;
      case 'wallet_address':
        data.wallet_address = ParseValue(value, DataType.string) as string | null;
        break;
      case 'perfil':
        data.perfil = ParseValue(value, DataType.enumeration) as UsuarioPerfil;
        break;
    }
  }
  
  return data as UsuarioModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for Email fields
 */
function createIndexEmail(
  email: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, email, 'email'),
  ];

  return {
    fields: ['email'],
    values
  };
}
/**
 * Create index for CpfCnpj fields
 */
function createIndexCpfCnpj(
  cpf_cnpj: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, cpf_cnpj, 'cpf_cnpj'),
  ];

  return {
    fields: ['cpf_cnpj'],
    values
  };
}
/**
 * Create index for WalletAddress fields
 */
function createIndexWalletAddress(
  wallet_address: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, wallet_address, 'wallet_address'),
  ];

  return {
    fields: ['wallet_address'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default UsuarioORM;