// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: garantia.
// - Entity ID: 102019b932bc3f077c3acf58292af054c33.
// - Entity Version: 102019bce3bf5b07679974e1d0aa86f47f5.
// - Task ID: 696c1755bcaec6128e359044.
// - Task Root ID: 695cef7bc0662b03161297fc.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for GarantiaStatusBloqueio
 */
export enum GarantiaStatusBloqueio {
  Unspecified = 0,
  Bloqueado = 1,
  Liberado = 2,
  Parcial = 3,
}



/**
 * Interface for GarantiaModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface GarantiaModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  contract_id: string;
  garantidor_id: string;
  imovel_garantia_id: string;
  valor_avaliado: number;
  status_bloqueio: GarantiaStatusBloqueio;
  margem_disponivel: number;
  data_bloqueio?: string | null;
  data_liberacao?: string | null;
}

/**
 * ORM class for Garantia entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class GarantiaORM {
  private static instance: GarantiaORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b932bc3f077c3acf58292af054c33';
    this.entityName = 'garantia';
    this.entityVersion = '102019bce3bf5b07679974e1d0aa86f47f5';
    this.taskId = '696c1755bcaec6128e359044';
    this.taskRootId = '695cef7bc0662b03161297fc';
  }

  /**
   * Get singleton instance of GarantiaORM
   */
  public static getInstance(): GarantiaORM {
    if (!GarantiaORM.instance) {
      GarantiaORM.instance = new GarantiaORM();
    }
    
    return GarantiaORM.instance;
  }

  /**
   * Get garantia by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getGarantiaByIDs(ids: string[]): Promise<GarantiaModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete garantia by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteGarantiaByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Garantia records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllGarantia(): Promise<GarantiaModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Garantia record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertGarantia(data: GarantiaModel[]): Promise<GarantiaModel[]> {
    const structured = data.map((item) => CreateData(GarantiaModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Garantia records
   */
  async purgeAllGarantia(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Garantia records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listGarantia(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[GarantiaModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get garantia by Id index
   * This function gets data by index.
   */
  async getGarantiaById(
    id: string,
  ): Promise<GarantiaModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) garantia by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGarantiaById(
    id: string,
    data: GarantiaModel
  ): Promise<GarantiaModel[]> {
    const index = createIndexId(
      id
    );

    const values = GarantiaModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete garantia by Id index
   */
  async deleteGarantiaById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get garantia by ContractId index
   * This function gets data by index.
   */
  async getGarantiaByContractId(
    contract_id: string,
  ): Promise<GarantiaModel[]> {
    const index = createIndexContractId(
      contract_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) garantia by ContractId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGarantiaByContractId(
    contract_id: string,
    data: GarantiaModel
  ): Promise<GarantiaModel[]> {
    const index = createIndexContractId(
      contract_id
    );

    const values = GarantiaModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete garantia by ContractId index
   */
  async deleteGarantiaByContractId(
    contract_id: string
  ): Promise<void> {
    const index = createIndexContractId(
      contract_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get garantia by GarantidorId index
   * This function gets data by index.
   */
  async getGarantiaByGarantidorId(
    garantidor_id: string,
  ): Promise<GarantiaModel[]> {
    const index = createIndexGarantidorId(
      garantidor_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) garantia by GarantidorId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGarantiaByGarantidorId(
    garantidor_id: string,
    data: GarantiaModel
  ): Promise<GarantiaModel[]> {
    const index = createIndexGarantidorId(
      garantidor_id
    );

    const values = GarantiaModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete garantia by GarantidorId index
   */
  async deleteGarantiaByGarantidorId(
    garantidor_id: string
  ): Promise<void> {
    const index = createIndexGarantidorId(
      garantidor_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get garantia by ImovelGarantiaId index
   * This function gets data by index.
   */
  async getGarantiaByImovelGarantiaId(
    imovel_garantia_id: string,
  ): Promise<GarantiaModel[]> {
    const index = createIndexImovelGarantiaId(
      imovel_garantia_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) garantia by ImovelGarantiaId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGarantiaByImovelGarantiaId(
    imovel_garantia_id: string,
    data: GarantiaModel
  ): Promise<GarantiaModel[]> {
    const index = createIndexImovelGarantiaId(
      imovel_garantia_id
    );

    const values = GarantiaModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete garantia by ImovelGarantiaId index
   */
  async deleteGarantiaByImovelGarantiaId(
    imovel_garantia_id: string
  ): Promise<void> {
    const index = createIndexImovelGarantiaId(
      imovel_garantia_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get garantia by DataCreator index
   * This function gets data by index.
   */
  async getGarantiaByDataCreator(
    data_creator: string,
  ): Promise<GarantiaModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) garantia by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGarantiaByDataCreator(
    data_creator: string,
    data: GarantiaModel
  ): Promise<GarantiaModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = GarantiaModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete garantia by DataCreator index
   */
  async deleteGarantiaByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get garantia by DataUpdater index
   * This function gets data by index.
   */
  async getGarantiaByDataUpdater(
    data_updater: string,
  ): Promise<GarantiaModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) garantia by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGarantiaByDataUpdater(
    data_updater: string,
    data: GarantiaModel
  ): Promise<GarantiaModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = GarantiaModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete garantia by DataUpdater index
   */
  async deleteGarantiaByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to GarantiaModel data array
   */
  private resultToData(values: Data[]): GarantiaModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return GarantiaModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as GarantiaModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized GarantiaModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is GarantiaModel => item !== null);
  }
}

/**
 * Convert GarantiaModel data to Value array
 */
function GarantiaModelToValues(data: GarantiaModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'contract_id', type: DataType.string, defaultValue: '' },
    { key: 'garantidor_id', type: DataType.string, defaultValue: '' },
    { key: 'imovel_garantia_id', type: DataType.string, defaultValue: '' },
    { key: 'valor_avaliado', type: DataType.number, defaultValue: 0 },
    { key: 'status_bloqueio', type: DataType.enumeration, defaultValue: 0 },
    { key: 'margem_disponivel', type: DataType.number, defaultValue: 0 },
    { key: 'data_bloqueio', type: DataType.string, defaultValue: null },
    { key: 'data_liberacao', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof GarantiaModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to GarantiaModel data
 */
function GarantiaModelFromValues(values: Value[]): GarantiaModel {
  const data: Partial<GarantiaModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'contract_id':
        data.contract_id = ParseValue(value, DataType.string) as string;
        break;
      case 'garantidor_id':
        data.garantidor_id = ParseValue(value, DataType.string) as string;
        break;
      case 'imovel_garantia_id':
        data.imovel_garantia_id = ParseValue(value, DataType.string) as string;
        break;
      case 'valor_avaliado':
        data.valor_avaliado = ParseValue(value, DataType.number) as number;
        break;
      case 'status_bloqueio':
        data.status_bloqueio = ParseValue(value, DataType.enumeration) as GarantiaStatusBloqueio;
        break;
      case 'margem_disponivel':
        data.margem_disponivel = ParseValue(value, DataType.number) as number;
        break;
      case 'data_bloqueio':
        data.data_bloqueio = ParseValue(value, DataType.string) as string | null;
        break;
      case 'data_liberacao':
        data.data_liberacao = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as GarantiaModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for ContractId fields
 */
function createIndexContractId(
  contract_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, contract_id, 'contract_id'),
  ];

  return {
    fields: ['contract_id'],
    values
  };
}
/**
 * Create index for GarantidorId fields
 */
function createIndexGarantidorId(
  garantidor_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, garantidor_id, 'garantidor_id'),
  ];

  return {
    fields: ['garantidor_id'],
    values
  };
}
/**
 * Create index for ImovelGarantiaId fields
 */
function createIndexImovelGarantiaId(
  imovel_garantia_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, imovel_garantia_id, 'imovel_garantia_id'),
  ];

  return {
    fields: ['imovel_garantia_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default GarantiaORM;