// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: contrato.
// - Entity ID: 102019b932a38bf73c9ad180a4e10015b5d.
// - Entity Version: 102019bce3bf5b07679974e1d0aa86f47f5.
// - Task ID: 696c1755bcaec6128e359044.
// - Task Root ID: 695cef7bc0662b03161297fc.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for ContratoStatus
 */
export enum ContratoStatus {
  Unspecified = 0,
  Draft = 1,
  Active = 2,
  Terminated = 3,
  Completed = 4,
}



/**
 * Interface for ContratoModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ContratoModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  locador_id: string;
  locatario_id: string;
  imovel_id: string;
  valor_aluguel: number;
  status: ContratoStatus;
}

/**
 * ORM class for Contrato entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ContratoORM {
  private static instance: ContratoORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b932a38bf73c9ad180a4e10015b5d';
    this.entityName = 'contrato';
    this.entityVersion = '102019bce3bf5b07679974e1d0aa86f47f5';
    this.taskId = '696c1755bcaec6128e359044';
    this.taskRootId = '695cef7bc0662b03161297fc';
  }

  /**
   * Get singleton instance of ContratoORM
   */
  public static getInstance(): ContratoORM {
    if (!ContratoORM.instance) {
      ContratoORM.instance = new ContratoORM();
    }
    
    return ContratoORM.instance;
  }

  /**
   * Get contrato by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getContratoByIDs(ids: string[]): Promise<ContratoModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete contrato by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteContratoByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Contrato records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllContrato(): Promise<ContratoModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Contrato record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertContrato(data: ContratoModel[]): Promise<ContratoModel[]> {
    const structured = data.map((item) => CreateData(ContratoModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Contrato records
   */
  async purgeAllContrato(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Contrato records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listContrato(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ContratoModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get contrato by Id index
   * This function gets data by index.
   */
  async getContratoById(
    id: string,
  ): Promise<ContratoModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) contrato by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setContratoById(
    id: string,
    data: ContratoModel
  ): Promise<ContratoModel[]> {
    const index = createIndexId(
      id
    );

    const values = ContratoModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete contrato by Id index
   */
  async deleteContratoById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get contrato by LocadorId index
   * This function gets data by index.
   */
  async getContratoByLocadorId(
    locador_id: string,
  ): Promise<ContratoModel[]> {
    const index = createIndexLocadorId(
      locador_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) contrato by LocadorId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setContratoByLocadorId(
    locador_id: string,
    data: ContratoModel
  ): Promise<ContratoModel[]> {
    const index = createIndexLocadorId(
      locador_id
    );

    const values = ContratoModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete contrato by LocadorId index
   */
  async deleteContratoByLocadorId(
    locador_id: string
  ): Promise<void> {
    const index = createIndexLocadorId(
      locador_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get contrato by LocatarioId index
   * This function gets data by index.
   */
  async getContratoByLocatarioId(
    locatario_id: string,
  ): Promise<ContratoModel[]> {
    const index = createIndexLocatarioId(
      locatario_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) contrato by LocatarioId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setContratoByLocatarioId(
    locatario_id: string,
    data: ContratoModel
  ): Promise<ContratoModel[]> {
    const index = createIndexLocatarioId(
      locatario_id
    );

    const values = ContratoModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete contrato by LocatarioId index
   */
  async deleteContratoByLocatarioId(
    locatario_id: string
  ): Promise<void> {
    const index = createIndexLocatarioId(
      locatario_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get contrato by ImovelId index
   * This function gets data by index.
   */
  async getContratoByImovelId(
    imovel_id: string,
  ): Promise<ContratoModel[]> {
    const index = createIndexImovelId(
      imovel_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) contrato by ImovelId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setContratoByImovelId(
    imovel_id: string,
    data: ContratoModel
  ): Promise<ContratoModel[]> {
    const index = createIndexImovelId(
      imovel_id
    );

    const values = ContratoModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete contrato by ImovelId index
   */
  async deleteContratoByImovelId(
    imovel_id: string
  ): Promise<void> {
    const index = createIndexImovelId(
      imovel_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get contrato by DataCreator index
   * This function gets data by index.
   */
  async getContratoByDataCreator(
    data_creator: string,
  ): Promise<ContratoModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) contrato by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setContratoByDataCreator(
    data_creator: string,
    data: ContratoModel
  ): Promise<ContratoModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ContratoModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete contrato by DataCreator index
   */
  async deleteContratoByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get contrato by DataUpdater index
   * This function gets data by index.
   */
  async getContratoByDataUpdater(
    data_updater: string,
  ): Promise<ContratoModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) contrato by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setContratoByDataUpdater(
    data_updater: string,
    data: ContratoModel
  ): Promise<ContratoModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ContratoModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete contrato by DataUpdater index
   */
  async deleteContratoByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ContratoModel data array
   */
  private resultToData(values: Data[]): ContratoModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ContratoModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ContratoModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ContratoModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ContratoModel => item !== null);
  }
}

/**
 * Convert ContratoModel data to Value array
 */
function ContratoModelToValues(data: ContratoModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'locador_id', type: DataType.string, defaultValue: '' },
    { key: 'locatario_id', type: DataType.string, defaultValue: '' },
    { key: 'imovel_id', type: DataType.string, defaultValue: '' },
    { key: 'valor_aluguel', type: DataType.number, defaultValue: 0 },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ContratoModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ContratoModel data
 */
function ContratoModelFromValues(values: Value[]): ContratoModel {
  const data: Partial<ContratoModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'locador_id':
        data.locador_id = ParseValue(value, DataType.string) as string;
        break;
      case 'locatario_id':
        data.locatario_id = ParseValue(value, DataType.string) as string;
        break;
      case 'imovel_id':
        data.imovel_id = ParseValue(value, DataType.string) as string;
        break;
      case 'valor_aluguel':
        data.valor_aluguel = ParseValue(value, DataType.number) as number;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as ContratoStatus;
        break;
    }
  }
  
  return data as ContratoModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for LocadorId fields
 */
function createIndexLocadorId(
  locador_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, locador_id, 'locador_id'),
  ];

  return {
    fields: ['locador_id'],
    values
  };
}
/**
 * Create index for LocatarioId fields
 */
function createIndexLocatarioId(
  locatario_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, locatario_id, 'locatario_id'),
  ];

  return {
    fields: ['locatario_id'],
    values
  };
}
/**
 * Create index for ImovelId fields
 */
function createIndexImovelId(
  imovel_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, imovel_id, 'imovel_id'),
  ];

  return {
    fields: ['imovel_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default ContratoORM;