// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: bi_metricas.
// - Entity ID: 102019b933136767a899345acbb4694d6ab.
// - Entity Version: 102019bce3bf5b07679974e1d0aa86f47f5.
// - Task ID: 696c1755bcaec6128e359044.
// - Task Root ID: 695cef7bc0662b03161297fc.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for BiMetricasModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface BiMetricasModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  periodo: string;
  ltv_medio: number;
  churn_rate: number;
  taxa_inadimplencia: number;
  total_contratos_ativos: number;
  total_nfts_mintados: number;
  receita_mensal: number;
  sinistros_count: number;
}

/**
 * ORM class for BiMetricas entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class BiMetricasORM {
  private static instance: BiMetricasORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b933136767a899345acbb4694d6ab';
    this.entityName = 'bi_metricas';
    this.entityVersion = '102019bce3bf5b07679974e1d0aa86f47f5';
    this.taskId = '696c1755bcaec6128e359044';
    this.taskRootId = '695cef7bc0662b03161297fc';
  }

  /**
   * Get singleton instance of BiMetricasORM
   */
  public static getInstance(): BiMetricasORM {
    if (!BiMetricasORM.instance) {
      BiMetricasORM.instance = new BiMetricasORM();
    }
    
    return BiMetricasORM.instance;
  }

  /**
   * Get bi_metricas by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getBiMetricasByIDs(ids: string[]): Promise<BiMetricasModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete bi_metricas by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteBiMetricasByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all BiMetricas records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllBiMetricas(): Promise<BiMetricasModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new BiMetricas record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertBiMetricas(data: BiMetricasModel[]): Promise<BiMetricasModel[]> {
    const structured = data.map((item) => CreateData(BiMetricasModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all BiMetricas records
   */
  async purgeAllBiMetricas(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List BiMetricas records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listBiMetricas(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[BiMetricasModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get bi_metricas by Id index
   * This function gets data by index.
   */
  async getBiMetricasById(
    id: string,
  ): Promise<BiMetricasModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) bi_metricas by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBiMetricasById(
    id: string,
    data: BiMetricasModel
  ): Promise<BiMetricasModel[]> {
    const index = createIndexId(
      id
    );

    const values = BiMetricasModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete bi_metricas by Id index
   */
  async deleteBiMetricasById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get bi_metricas by Periodo index
   * This function gets data by index.
   */
  async getBiMetricasByPeriodo(
    periodo: string,
  ): Promise<BiMetricasModel[]> {
    const index = createIndexPeriodo(
      periodo
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) bi_metricas by Periodo index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBiMetricasByPeriodo(
    periodo: string,
    data: BiMetricasModel
  ): Promise<BiMetricasModel[]> {
    const index = createIndexPeriodo(
      periodo
    );

    const values = BiMetricasModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete bi_metricas by Periodo index
   */
  async deleteBiMetricasByPeriodo(
    periodo: string
  ): Promise<void> {
    const index = createIndexPeriodo(
      periodo
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get bi_metricas by DataCreator index
   * This function gets data by index.
   */
  async getBiMetricasByDataCreator(
    data_creator: string,
  ): Promise<BiMetricasModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) bi_metricas by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBiMetricasByDataCreator(
    data_creator: string,
    data: BiMetricasModel
  ): Promise<BiMetricasModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = BiMetricasModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete bi_metricas by DataCreator index
   */
  async deleteBiMetricasByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get bi_metricas by DataUpdater index
   * This function gets data by index.
   */
  async getBiMetricasByDataUpdater(
    data_updater: string,
  ): Promise<BiMetricasModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) bi_metricas by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBiMetricasByDataUpdater(
    data_updater: string,
    data: BiMetricasModel
  ): Promise<BiMetricasModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = BiMetricasModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete bi_metricas by DataUpdater index
   */
  async deleteBiMetricasByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to BiMetricasModel data array
   */
  private resultToData(values: Data[]): BiMetricasModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return BiMetricasModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as BiMetricasModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized BiMetricasModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is BiMetricasModel => item !== null);
  }
}

/**
 * Convert BiMetricasModel data to Value array
 */
function BiMetricasModelToValues(data: BiMetricasModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'periodo', type: DataType.string, defaultValue: '' },
    { key: 'ltv_medio', type: DataType.number, defaultValue: 0 },
    { key: 'churn_rate', type: DataType.number, defaultValue: 0 },
    { key: 'taxa_inadimplencia', type: DataType.number, defaultValue: 0 },
    { key: 'total_contratos_ativos', type: DataType.number, defaultValue: 0 },
    { key: 'total_nfts_mintados', type: DataType.number, defaultValue: 0 },
    { key: 'receita_mensal', type: DataType.number, defaultValue: 0 },
    { key: 'sinistros_count', type: DataType.number, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof BiMetricasModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to BiMetricasModel data
 */
function BiMetricasModelFromValues(values: Value[]): BiMetricasModel {
  const data: Partial<BiMetricasModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'periodo':
        data.periodo = ParseValue(value, DataType.string) as string;
        break;
      case 'ltv_medio':
        data.ltv_medio = ParseValue(value, DataType.number) as number;
        break;
      case 'churn_rate':
        data.churn_rate = ParseValue(value, DataType.number) as number;
        break;
      case 'taxa_inadimplencia':
        data.taxa_inadimplencia = ParseValue(value, DataType.number) as number;
        break;
      case 'total_contratos_ativos':
        data.total_contratos_ativos = ParseValue(value, DataType.number) as number;
        break;
      case 'total_nfts_mintados':
        data.total_nfts_mintados = ParseValue(value, DataType.number) as number;
        break;
      case 'receita_mensal':
        data.receita_mensal = ParseValue(value, DataType.number) as number;
        break;
      case 'sinistros_count':
        data.sinistros_count = ParseValue(value, DataType.number) as number;
        break;
    }
  }
  
  return data as BiMetricasModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for Periodo fields
 */
function createIndexPeriodo(
  periodo: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, periodo, 'periodo'),
  ];

  return {
    fields: ['periodo'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default BiMetricasORM;