// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: auditoria_blockchain.
// - Entity ID: 102019b932d80167a819e3a769aa5f57b49.
// - Entity Version: 102019bce3bf5b07679974e1d0aa86f47f5.
// - Task ID: 696c1755bcaec6128e359044.
// - Task Root ID: 695cef7bc0662b03161297fc.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for AuditoriaBlockchainAcao
 */
export enum AuditoriaBlockchainAcao {
  Unspecified = 0,
  Mint = 1,
  Transfer = 2,
  Burn = 3,
  Update = 4,
  Lock = 5,
  Unlock = 6,
}
/**
 * Enumeration for AuditoriaBlockchainEntidadeTipo
 */
export enum AuditoriaBlockchainEntidadeTipo {
  Unspecified = 0,
  Contrato = 1,
  Transacao = 2,
  Garantia = 3,
  NFT = 4,
}



/**
 * Interface for AuditoriaBlockchainModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface AuditoriaBlockchainModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  entidade_tipo: AuditoriaBlockchainEntidadeTipo;
  entidade_id: string;
  acao: AuditoriaBlockchainAcao;
  hash_blockchain: string;
  gas_fee: number;
  user_id: string;
  metadata?: string | null;
}

/**
 * ORM class for AuditoriaBlockchain entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class AuditoriaBlockchainORM {
  private static instance: AuditoriaBlockchainORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b932d80167a819e3a769aa5f57b49';
    this.entityName = 'auditoria_blockchain';
    this.entityVersion = '102019bce3bf5b07679974e1d0aa86f47f5';
    this.taskId = '696c1755bcaec6128e359044';
    this.taskRootId = '695cef7bc0662b03161297fc';
  }

  /**
   * Get singleton instance of AuditoriaBlockchainORM
   */
  public static getInstance(): AuditoriaBlockchainORM {
    if (!AuditoriaBlockchainORM.instance) {
      AuditoriaBlockchainORM.instance = new AuditoriaBlockchainORM();
    }
    
    return AuditoriaBlockchainORM.instance;
  }

  /**
   * Get auditoria_blockchain by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getAuditoriaBlockchainByIDs(ids: string[]): Promise<AuditoriaBlockchainModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete auditoria_blockchain by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteAuditoriaBlockchainByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all AuditoriaBlockchain records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllAuditoriaBlockchain(): Promise<AuditoriaBlockchainModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new AuditoriaBlockchain record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertAuditoriaBlockchain(data: AuditoriaBlockchainModel[]): Promise<AuditoriaBlockchainModel[]> {
    const structured = data.map((item) => CreateData(AuditoriaBlockchainModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all AuditoriaBlockchain records
   */
  async purgeAllAuditoriaBlockchain(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List AuditoriaBlockchain records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listAuditoriaBlockchain(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[AuditoriaBlockchainModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get auditoria_blockchain by Id index
   * This function gets data by index.
   */
  async getAuditoriaBlockchainById(
    id: string,
  ): Promise<AuditoriaBlockchainModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) auditoria_blockchain by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAuditoriaBlockchainById(
    id: string,
    data: AuditoriaBlockchainModel
  ): Promise<AuditoriaBlockchainModel[]> {
    const index = createIndexId(
      id
    );

    const values = AuditoriaBlockchainModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete auditoria_blockchain by Id index
   */
  async deleteAuditoriaBlockchainById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get auditoria_blockchain by HashBlockchain index
   * This function gets data by index.
   */
  async getAuditoriaBlockchainByHashBlockchain(
    hash_blockchain: string,
  ): Promise<AuditoriaBlockchainModel[]> {
    const index = createIndexHashBlockchain(
      hash_blockchain
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) auditoria_blockchain by HashBlockchain index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAuditoriaBlockchainByHashBlockchain(
    hash_blockchain: string,
    data: AuditoriaBlockchainModel
  ): Promise<AuditoriaBlockchainModel[]> {
    const index = createIndexHashBlockchain(
      hash_blockchain
    );

    const values = AuditoriaBlockchainModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete auditoria_blockchain by HashBlockchain index
   */
  async deleteAuditoriaBlockchainByHashBlockchain(
    hash_blockchain: string
  ): Promise<void> {
    const index = createIndexHashBlockchain(
      hash_blockchain
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get auditoria_blockchain by UserId index
   * This function gets data by index.
   */
  async getAuditoriaBlockchainByUserId(
    user_id: string,
  ): Promise<AuditoriaBlockchainModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) auditoria_blockchain by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAuditoriaBlockchainByUserId(
    user_id: string,
    data: AuditoriaBlockchainModel
  ): Promise<AuditoriaBlockchainModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = AuditoriaBlockchainModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete auditoria_blockchain by UserId index
   */
  async deleteAuditoriaBlockchainByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get auditoria_blockchain by EntidadeIdEntidadeTipo index
   * This function gets data by index.
   */
  async getAuditoriaBlockchainByEntidadeIdEntidadeTipo(
    entidade_id: string,
    entidade_tipo: AuditoriaBlockchainEntidadeTipo,
  ): Promise<AuditoriaBlockchainModel[]> {
    const index = createIndexEntidadeIdEntidadeTipo(
      entidade_id,
      entidade_tipo
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) auditoria_blockchain by EntidadeIdEntidadeTipo index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAuditoriaBlockchainByEntidadeIdEntidadeTipo(
    entidade_id: string,
    entidade_tipo: AuditoriaBlockchainEntidadeTipo,
    data: AuditoriaBlockchainModel
  ): Promise<AuditoriaBlockchainModel[]> {
    const index = createIndexEntidadeIdEntidadeTipo(
      entidade_id,
      entidade_tipo
    );

    const values = AuditoriaBlockchainModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete auditoria_blockchain by EntidadeIdEntidadeTipo index
   */
  async deleteAuditoriaBlockchainByEntidadeIdEntidadeTipo(
    entidade_id: string,
    entidade_tipo: AuditoriaBlockchainEntidadeTipo
  ): Promise<void> {
    const index = createIndexEntidadeIdEntidadeTipo(
      entidade_id,
      entidade_tipo
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get auditoria_blockchain by DataCreator index
   * This function gets data by index.
   */
  async getAuditoriaBlockchainByDataCreator(
    data_creator: string,
  ): Promise<AuditoriaBlockchainModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) auditoria_blockchain by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAuditoriaBlockchainByDataCreator(
    data_creator: string,
    data: AuditoriaBlockchainModel
  ): Promise<AuditoriaBlockchainModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = AuditoriaBlockchainModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete auditoria_blockchain by DataCreator index
   */
  async deleteAuditoriaBlockchainByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get auditoria_blockchain by DataUpdater index
   * This function gets data by index.
   */
  async getAuditoriaBlockchainByDataUpdater(
    data_updater: string,
  ): Promise<AuditoriaBlockchainModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) auditoria_blockchain by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAuditoriaBlockchainByDataUpdater(
    data_updater: string,
    data: AuditoriaBlockchainModel
  ): Promise<AuditoriaBlockchainModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = AuditoriaBlockchainModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete auditoria_blockchain by DataUpdater index
   */
  async deleteAuditoriaBlockchainByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to AuditoriaBlockchainModel data array
   */
  private resultToData(values: Data[]): AuditoriaBlockchainModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return AuditoriaBlockchainModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as AuditoriaBlockchainModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized AuditoriaBlockchainModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is AuditoriaBlockchainModel => item !== null);
  }
}

/**
 * Convert AuditoriaBlockchainModel data to Value array
 */
function AuditoriaBlockchainModelToValues(data: AuditoriaBlockchainModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'entidade_tipo', type: DataType.enumeration, defaultValue: 0 },
    { key: 'entidade_id', type: DataType.string, defaultValue: '' },
    { key: 'acao', type: DataType.enumeration, defaultValue: 0 },
    { key: 'hash_blockchain', type: DataType.string, defaultValue: '' },
    { key: 'gas_fee', type: DataType.number, defaultValue: 0 },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'metadata', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof AuditoriaBlockchainModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to AuditoriaBlockchainModel data
 */
function AuditoriaBlockchainModelFromValues(values: Value[]): AuditoriaBlockchainModel {
  const data: Partial<AuditoriaBlockchainModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'entidade_tipo':
        data.entidade_tipo = ParseValue(value, DataType.enumeration) as AuditoriaBlockchainEntidadeTipo;
        break;
      case 'entidade_id':
        data.entidade_id = ParseValue(value, DataType.string) as string;
        break;
      case 'acao':
        data.acao = ParseValue(value, DataType.enumeration) as AuditoriaBlockchainAcao;
        break;
      case 'hash_blockchain':
        data.hash_blockchain = ParseValue(value, DataType.string) as string;
        break;
      case 'gas_fee':
        data.gas_fee = ParseValue(value, DataType.number) as number;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'metadata':
        data.metadata = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as AuditoriaBlockchainModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for HashBlockchain fields
 */
function createIndexHashBlockchain(
  hash_blockchain: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, hash_blockchain, 'hash_blockchain'),
  ];

  return {
    fields: ['hash_blockchain'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for EntidadeIdEntidadeTipo fields
 */
function createIndexEntidadeIdEntidadeTipo(
  entidade_id: string,
  entidade_tipo: AuditoriaBlockchainEntidadeTipo
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, entidade_id, 'entidade_id'),
    CreateValue(DataType.enumeration, entidade_tipo, 'entidade_tipo'),
  ];

  return {
    fields: ['entidade_id', 'entidade_tipo'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default AuditoriaBlockchainORM;