/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VerificarImport } from './routes/verificar'
import { Route as SimuladorImport } from './routes/simulador'
import { Route as SetupImport } from './routes/setup'
import { Route as P2pImport } from './routes/p2p'
import { Route as MarketplaceImport } from './routes/marketplace'
import { Route as InvestidorImport } from './routes/investidor'
import { Route as InquilinosImport } from './routes/inquilinos'
import { Route as GarantidoresImport } from './routes/garantidores'
import { Route as ClubeVbrzImport } from './routes/clube-vbrz'
import { Route as IndexImport } from './routes/index'
import { Route as TenantSupportImport } from './routes/tenant/support'
import { Route as TenantProfileImport } from './routes/tenant/profile'
import { Route as TenantPaymentsImport } from './routes/tenant/payments'
import { Route as TenantJourneyImport } from './routes/tenant/journey'
import { Route as TenantDashboardImport } from './routes/tenant/dashboard'
import { Route as TenantContractImport } from './routes/tenant/contract'
import { Route as LocadorAreaImport } from './routes/locador/area'
import { Route as LandlordMyContractsImport } from './routes/landlord/my-contracts'
import { Route as InvestorMarketplaceImport } from './routes/investor/marketplace'
import { Route as InquilinoAreaImport } from './routes/inquilino/area'
import { Route as ImobSlugImport } from './routes/imob/$slug'
import { Route as GarantidorTermoImport } from './routes/garantidor/termo'
import { Route as GarantidorAreaImport } from './routes/garantidor/area'
import { Route as AuthRegisterSuperhostImport } from './routes/auth/register-superhost'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AssetsSuccessImport } from './routes/assets/success'
import { Route as AssetsPendingImport } from './routes/assets/pending'
import { Route as AssetsNewImport } from './routes/assets/new'
import { Route as AgencyWelcomeImport } from './routes/agency/welcome'
import { Route as AgencySupportImport } from './routes/agency/support'
import { Route as AgencySplitCalculatorImport } from './routes/agency/split-calculator'
import { Route as AgencySiteImport } from './routes/agency/site'
import { Route as AgencySetupImport } from './routes/agency/setup'
import { Route as AgencySettingsImport } from './routes/agency/settings'
import { Route as AgencyOwnersImport } from './routes/agency/owners'
import { Route as AgencyFinancialImport } from './routes/agency/financial'
import { Route as AgencyContractsImport } from './routes/agency/contracts'
import { Route as AgencyAdsImport } from './routes/agency/ads'
import { Route as AdminVbrzTokenImport } from './routes/admin/vbrz-token'
import { Route as AdminUsersImport } from './routes/admin/users'
import { Route as AdminSupportMonitorImport } from './routes/admin/support-monitor'
import { Route as AdminSmtpImport } from './routes/admin/smtp'
import { Route as AdminSettingsImport } from './routes/admin/settings'
import { Route as AdminRolesImport } from './routes/admin/roles'
import { Route as AdminPropertiesImport } from './routes/admin/properties'
import { Route as AdminProfileImport } from './routes/admin/profile'
import { Route as AdminPermissionsImport } from './routes/admin/permissions'
import { Route as AdminOmnichannelImport } from './routes/admin/omnichannel'
import { Route as AdminNftRegistryImport } from './routes/admin/nft-registry'
import { Route as AdminMarketplaceImport } from './routes/admin/marketplace'
import { Route as AdminInvestmentsImport } from './routes/admin/investments'
import { Route as AdminIntegrationsImport } from './routes/admin/integrations'
import { Route as AdminInspectionImport } from './routes/admin/inspection'
import { Route as AdminHelpImport } from './routes/admin/help'
import { Route as AdminGithubImport } from './routes/admin/github'
import { Route as AdminFlowBuilderImport } from './routes/admin/flow-builder'
import { Route as AdminFinanceiroImport } from './routes/admin/financeiro'
import { Route as AdminFeatureFlagsImport } from './routes/admin/feature-flags'
import { Route as AdminEngageImport } from './routes/admin/engage'
import { Route as AdminDocsImport } from './routes/admin/docs'
import { Route as AdminDefiImport } from './routes/admin/defi'
import { Route as AdminDashboardsConsultivasImport } from './routes/admin/dashboards-consultivas'
import { Route as AdminDashboardImport } from './routes/admin/dashboard'
import { Route as AdminCrmLiveImport } from './routes/admin/crm-live'
import { Route as AdminContractsImport } from './routes/admin/contracts'
import { Route as AdminContactImport } from './routes/admin/contact'
import { Route as AdminCommunicationImport } from './routes/admin/communication'
import { Route as AdminChangelogImport } from './routes/admin/changelog'
import { Route as AdminCashbackImport } from './routes/admin/cashback'
import { Route as AdminAuditoriaImport } from './routes/admin/auditoria'
import { Route as AdminAnalyticsImport } from './routes/admin/analytics'
import { Route as AdminAgenciesImport } from './routes/admin/agencies'
import { Route as AdminAdsImport } from './routes/admin/ads'
import { Route as AdminAboutImport } from './routes/admin/about'
import { Route as DashboardAssetsIndexImport } from './routes/dashboard/assets/index'
import { Route as AgencyPropertiesIndexImport } from './routes/agency/properties/index'
import { Route as AgencyDashboardIndexImport } from './routes/agency/dashboard/index'
import { Route as AgencyPropertiesNewImport } from './routes/agency/properties/new'

// Create/Update Routes

const VerificarRoute = VerificarImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => rootRoute,
} as any)

const SimuladorRoute = SimuladorImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRoute,
} as any)

const SetupRoute = SetupImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRoute,
} as any)

const P2pRoute = P2pImport.update({
  id: '/p2p',
  path: '/p2p',
  getParentRoute: () => rootRoute,
} as any)

const MarketplaceRoute = MarketplaceImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRoute,
} as any)

const InvestidorRoute = InvestidorImport.update({
  id: '/investidor',
  path: '/investidor',
  getParentRoute: () => rootRoute,
} as any)

const InquilinosRoute = InquilinosImport.update({
  id: '/inquilinos',
  path: '/inquilinos',
  getParentRoute: () => rootRoute,
} as any)

const GarantidoresRoute = GarantidoresImport.update({
  id: '/garantidores',
  path: '/garantidores',
  getParentRoute: () => rootRoute,
} as any)

const ClubeVbrzRoute = ClubeVbrzImport.update({
  id: '/clube-vbrz',
  path: '/clube-vbrz',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TenantSupportRoute = TenantSupportImport.update({
  id: '/tenant/support',
  path: '/tenant/support',
  getParentRoute: () => rootRoute,
} as any)

const TenantProfileRoute = TenantProfileImport.update({
  id: '/tenant/profile',
  path: '/tenant/profile',
  getParentRoute: () => rootRoute,
} as any)

const TenantPaymentsRoute = TenantPaymentsImport.update({
  id: '/tenant/payments',
  path: '/tenant/payments',
  getParentRoute: () => rootRoute,
} as any)

const TenantJourneyRoute = TenantJourneyImport.update({
  id: '/tenant/journey',
  path: '/tenant/journey',
  getParentRoute: () => rootRoute,
} as any)

const TenantDashboardRoute = TenantDashboardImport.update({
  id: '/tenant/dashboard',
  path: '/tenant/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const TenantContractRoute = TenantContractImport.update({
  id: '/tenant/contract',
  path: '/tenant/contract',
  getParentRoute: () => rootRoute,
} as any)

const LocadorAreaRoute = LocadorAreaImport.update({
  id: '/locador/area',
  path: '/locador/area',
  getParentRoute: () => rootRoute,
} as any)

const LandlordMyContractsRoute = LandlordMyContractsImport.update({
  id: '/landlord/my-contracts',
  path: '/landlord/my-contracts',
  getParentRoute: () => rootRoute,
} as any)

const InvestorMarketplaceRoute = InvestorMarketplaceImport.update({
  id: '/investor/marketplace',
  path: '/investor/marketplace',
  getParentRoute: () => rootRoute,
} as any)

const InquilinoAreaRoute = InquilinoAreaImport.update({
  id: '/inquilino/area',
  path: '/inquilino/area',
  getParentRoute: () => rootRoute,
} as any)

const ImobSlugRoute = ImobSlugImport.update({
  id: '/imob/$slug',
  path: '/imob/$slug',
  getParentRoute: () => rootRoute,
} as any)

const GarantidorTermoRoute = GarantidorTermoImport.update({
  id: '/garantidor/termo',
  path: '/garantidor/termo',
  getParentRoute: () => rootRoute,
} as any)

const GarantidorAreaRoute = GarantidorAreaImport.update({
  id: '/garantidor/area',
  path: '/garantidor/area',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterSuperhostRoute = AuthRegisterSuperhostImport.update({
  id: '/auth/register-superhost',
  path: '/auth/register-superhost',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AssetsSuccessRoute = AssetsSuccessImport.update({
  id: '/assets/success',
  path: '/assets/success',
  getParentRoute: () => rootRoute,
} as any)

const AssetsPendingRoute = AssetsPendingImport.update({
  id: '/assets/pending',
  path: '/assets/pending',
  getParentRoute: () => rootRoute,
} as any)

const AssetsNewRoute = AssetsNewImport.update({
  id: '/assets/new',
  path: '/assets/new',
  getParentRoute: () => rootRoute,
} as any)

const AgencyWelcomeRoute = AgencyWelcomeImport.update({
  id: '/agency/welcome',
  path: '/agency/welcome',
  getParentRoute: () => rootRoute,
} as any)

const AgencySupportRoute = AgencySupportImport.update({
  id: '/agency/support',
  path: '/agency/support',
  getParentRoute: () => rootRoute,
} as any)

const AgencySplitCalculatorRoute = AgencySplitCalculatorImport.update({
  id: '/agency/split-calculator',
  path: '/agency/split-calculator',
  getParentRoute: () => rootRoute,
} as any)

const AgencySiteRoute = AgencySiteImport.update({
  id: '/agency/site',
  path: '/agency/site',
  getParentRoute: () => rootRoute,
} as any)

const AgencySetupRoute = AgencySetupImport.update({
  id: '/agency/setup',
  path: '/agency/setup',
  getParentRoute: () => rootRoute,
} as any)

const AgencySettingsRoute = AgencySettingsImport.update({
  id: '/agency/settings',
  path: '/agency/settings',
  getParentRoute: () => rootRoute,
} as any)

const AgencyOwnersRoute = AgencyOwnersImport.update({
  id: '/agency/owners',
  path: '/agency/owners',
  getParentRoute: () => rootRoute,
} as any)

const AgencyFinancialRoute = AgencyFinancialImport.update({
  id: '/agency/financial',
  path: '/agency/financial',
  getParentRoute: () => rootRoute,
} as any)

const AgencyContractsRoute = AgencyContractsImport.update({
  id: '/agency/contracts',
  path: '/agency/contracts',
  getParentRoute: () => rootRoute,
} as any)

const AgencyAdsRoute = AgencyAdsImport.update({
  id: '/agency/ads',
  path: '/agency/ads',
  getParentRoute: () => rootRoute,
} as any)

const AdminVbrzTokenRoute = AdminVbrzTokenImport.update({
  id: '/admin/vbrz-token',
  path: '/admin/vbrz-token',
  getParentRoute: () => rootRoute,
} as any)

const AdminUsersRoute = AdminUsersImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRoute,
} as any)

const AdminSupportMonitorRoute = AdminSupportMonitorImport.update({
  id: '/admin/support-monitor',
  path: '/admin/support-monitor',
  getParentRoute: () => rootRoute,
} as any)

const AdminSmtpRoute = AdminSmtpImport.update({
  id: '/admin/smtp',
  path: '/admin/smtp',
  getParentRoute: () => rootRoute,
} as any)

const AdminSettingsRoute = AdminSettingsImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRoute,
} as any)

const AdminRolesRoute = AdminRolesImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRoute,
} as any)

const AdminPropertiesRoute = AdminPropertiesImport.update({
  id: '/admin/properties',
  path: '/admin/properties',
  getParentRoute: () => rootRoute,
} as any)

const AdminProfileRoute = AdminProfileImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRoute,
} as any)

const AdminPermissionsRoute = AdminPermissionsImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => rootRoute,
} as any)

const AdminOmnichannelRoute = AdminOmnichannelImport.update({
  id: '/admin/omnichannel',
  path: '/admin/omnichannel',
  getParentRoute: () => rootRoute,
} as any)

const AdminNftRegistryRoute = AdminNftRegistryImport.update({
  id: '/admin/nft-registry',
  path: '/admin/nft-registry',
  getParentRoute: () => rootRoute,
} as any)

const AdminMarketplaceRoute = AdminMarketplaceImport.update({
  id: '/admin/marketplace',
  path: '/admin/marketplace',
  getParentRoute: () => rootRoute,
} as any)

const AdminInvestmentsRoute = AdminInvestmentsImport.update({
  id: '/admin/investments',
  path: '/admin/investments',
  getParentRoute: () => rootRoute,
} as any)

const AdminIntegrationsRoute = AdminIntegrationsImport.update({
  id: '/admin/integrations',
  path: '/admin/integrations',
  getParentRoute: () => rootRoute,
} as any)

const AdminInspectionRoute = AdminInspectionImport.update({
  id: '/admin/inspection',
  path: '/admin/inspection',
  getParentRoute: () => rootRoute,
} as any)

const AdminHelpRoute = AdminHelpImport.update({
  id: '/admin/help',
  path: '/admin/help',
  getParentRoute: () => rootRoute,
} as any)

const AdminGithubRoute = AdminGithubImport.update({
  id: '/admin/github',
  path: '/admin/github',
  getParentRoute: () => rootRoute,
} as any)

const AdminFlowBuilderRoute = AdminFlowBuilderImport.update({
  id: '/admin/flow-builder',
  path: '/admin/flow-builder',
  getParentRoute: () => rootRoute,
} as any)

const AdminFinanceiroRoute = AdminFinanceiroImport.update({
  id: '/admin/financeiro',
  path: '/admin/financeiro',
  getParentRoute: () => rootRoute,
} as any)

const AdminFeatureFlagsRoute = AdminFeatureFlagsImport.update({
  id: '/admin/feature-flags',
  path: '/admin/feature-flags',
  getParentRoute: () => rootRoute,
} as any)

const AdminEngageRoute = AdminEngageImport.update({
  id: '/admin/engage',
  path: '/admin/engage',
  getParentRoute: () => rootRoute,
} as any)

const AdminDocsRoute = AdminDocsImport.update({
  id: '/admin/docs',
  path: '/admin/docs',
  getParentRoute: () => rootRoute,
} as any)

const AdminDefiRoute = AdminDefiImport.update({
  id: '/admin/defi',
  path: '/admin/defi',
  getParentRoute: () => rootRoute,
} as any)

const AdminDashboardsConsultivasRoute = AdminDashboardsConsultivasImport.update(
  {
    id: '/admin/dashboards-consultivas',
    path: '/admin/dashboards-consultivas',
    getParentRoute: () => rootRoute,
  } as any,
)

const AdminDashboardRoute = AdminDashboardImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AdminCrmLiveRoute = AdminCrmLiveImport.update({
  id: '/admin/crm-live',
  path: '/admin/crm-live',
  getParentRoute: () => rootRoute,
} as any)

const AdminContractsRoute = AdminContractsImport.update({
  id: '/admin/contracts',
  path: '/admin/contracts',
  getParentRoute: () => rootRoute,
} as any)

const AdminContactRoute = AdminContactImport.update({
  id: '/admin/contact',
  path: '/admin/contact',
  getParentRoute: () => rootRoute,
} as any)

const AdminCommunicationRoute = AdminCommunicationImport.update({
  id: '/admin/communication',
  path: '/admin/communication',
  getParentRoute: () => rootRoute,
} as any)

const AdminChangelogRoute = AdminChangelogImport.update({
  id: '/admin/changelog',
  path: '/admin/changelog',
  getParentRoute: () => rootRoute,
} as any)

const AdminCashbackRoute = AdminCashbackImport.update({
  id: '/admin/cashback',
  path: '/admin/cashback',
  getParentRoute: () => rootRoute,
} as any)

const AdminAuditoriaRoute = AdminAuditoriaImport.update({
  id: '/admin/auditoria',
  path: '/admin/auditoria',
  getParentRoute: () => rootRoute,
} as any)

const AdminAnalyticsRoute = AdminAnalyticsImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRoute,
} as any)

const AdminAgenciesRoute = AdminAgenciesImport.update({
  id: '/admin/agencies',
  path: '/admin/agencies',
  getParentRoute: () => rootRoute,
} as any)

const AdminAdsRoute = AdminAdsImport.update({
  id: '/admin/ads',
  path: '/admin/ads',
  getParentRoute: () => rootRoute,
} as any)

const AdminAboutRoute = AdminAboutImport.update({
  id: '/admin/about',
  path: '/admin/about',
  getParentRoute: () => rootRoute,
} as any)

const DashboardAssetsIndexRoute = DashboardAssetsIndexImport.update({
  id: '/dashboard/assets/',
  path: '/dashboard/assets/',
  getParentRoute: () => rootRoute,
} as any)

const AgencyPropertiesIndexRoute = AgencyPropertiesIndexImport.update({
  id: '/agency/properties/',
  path: '/agency/properties/',
  getParentRoute: () => rootRoute,
} as any)

const AgencyDashboardIndexRoute = AgencyDashboardIndexImport.update({
  id: '/agency/dashboard/',
  path: '/agency/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const AgencyPropertiesNewRoute = AgencyPropertiesNewImport.update({
  id: '/agency/properties/new',
  path: '/agency/properties/new',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/clube-vbrz': {
      id: '/clube-vbrz'
      path: '/clube-vbrz'
      fullPath: '/clube-vbrz'
      preLoaderRoute: typeof ClubeVbrzImport
      parentRoute: typeof rootRoute
    }
    '/garantidores': {
      id: '/garantidores'
      path: '/garantidores'
      fullPath: '/garantidores'
      preLoaderRoute: typeof GarantidoresImport
      parentRoute: typeof rootRoute
    }
    '/inquilinos': {
      id: '/inquilinos'
      path: '/inquilinos'
      fullPath: '/inquilinos'
      preLoaderRoute: typeof InquilinosImport
      parentRoute: typeof rootRoute
    }
    '/investidor': {
      id: '/investidor'
      path: '/investidor'
      fullPath: '/investidor'
      preLoaderRoute: typeof InvestidorImport
      parentRoute: typeof rootRoute
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceImport
      parentRoute: typeof rootRoute
    }
    '/p2p': {
      id: '/p2p'
      path: '/p2p'
      fullPath: '/p2p'
      preLoaderRoute: typeof P2pImport
      parentRoute: typeof rootRoute
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupImport
      parentRoute: typeof rootRoute
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorImport
      parentRoute: typeof rootRoute
    }
    '/verificar': {
      id: '/verificar'
      path: '/verificar'
      fullPath: '/verificar'
      preLoaderRoute: typeof VerificarImport
      parentRoute: typeof rootRoute
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/admin/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutImport
      parentRoute: typeof rootRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/admin/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsImport
      parentRoute: typeof rootRoute
    }
    '/admin/agencies': {
      id: '/admin/agencies'
      path: '/admin/agencies'
      fullPath: '/admin/agencies'
      preLoaderRoute: typeof AdminAgenciesImport
      parentRoute: typeof rootRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsImport
      parentRoute: typeof rootRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaImport
      parentRoute: typeof rootRoute
    }
    '/admin/cashback': {
      id: '/admin/cashback'
      path: '/admin/cashback'
      fullPath: '/admin/cashback'
      preLoaderRoute: typeof AdminCashbackImport
      parentRoute: typeof rootRoute
    }
    '/admin/changelog': {
      id: '/admin/changelog'
      path: '/admin/changelog'
      fullPath: '/admin/changelog'
      preLoaderRoute: typeof AdminChangelogImport
      parentRoute: typeof rootRoute
    }
    '/admin/communication': {
      id: '/admin/communication'
      path: '/admin/communication'
      fullPath: '/admin/communication'
      preLoaderRoute: typeof AdminCommunicationImport
      parentRoute: typeof rootRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/admin/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactImport
      parentRoute: typeof rootRoute
    }
    '/admin/contracts': {
      id: '/admin/contracts'
      path: '/admin/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AdminContractsImport
      parentRoute: typeof rootRoute
    }
    '/admin/crm-live': {
      id: '/admin/crm-live'
      path: '/admin/crm-live'
      fullPath: '/admin/crm-live'
      preLoaderRoute: typeof AdminCrmLiveImport
      parentRoute: typeof rootRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardImport
      parentRoute: typeof rootRoute
    }
    '/admin/dashboards-consultivas': {
      id: '/admin/dashboards-consultivas'
      path: '/admin/dashboards-consultivas'
      fullPath: '/admin/dashboards-consultivas'
      preLoaderRoute: typeof AdminDashboardsConsultivasImport
      parentRoute: typeof rootRoute
    }
    '/admin/defi': {
      id: '/admin/defi'
      path: '/admin/defi'
      fullPath: '/admin/defi'
      preLoaderRoute: typeof AdminDefiImport
      parentRoute: typeof rootRoute
    }
    '/admin/docs': {
      id: '/admin/docs'
      path: '/admin/docs'
      fullPath: '/admin/docs'
      preLoaderRoute: typeof AdminDocsImport
      parentRoute: typeof rootRoute
    }
    '/admin/engage': {
      id: '/admin/engage'
      path: '/admin/engage'
      fullPath: '/admin/engage'
      preLoaderRoute: typeof AdminEngageImport
      parentRoute: typeof rootRoute
    }
    '/admin/feature-flags': {
      id: '/admin/feature-flags'
      path: '/admin/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof AdminFeatureFlagsImport
      parentRoute: typeof rootRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/admin/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroImport
      parentRoute: typeof rootRoute
    }
    '/admin/flow-builder': {
      id: '/admin/flow-builder'
      path: '/admin/flow-builder'
      fullPath: '/admin/flow-builder'
      preLoaderRoute: typeof AdminFlowBuilderImport
      parentRoute: typeof rootRoute
    }
    '/admin/github': {
      id: '/admin/github'
      path: '/admin/github'
      fullPath: '/admin/github'
      preLoaderRoute: typeof AdminGithubImport
      parentRoute: typeof rootRoute
    }
    '/admin/help': {
      id: '/admin/help'
      path: '/admin/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AdminHelpImport
      parentRoute: typeof rootRoute
    }
    '/admin/inspection': {
      id: '/admin/inspection'
      path: '/admin/inspection'
      fullPath: '/admin/inspection'
      preLoaderRoute: typeof AdminInspectionImport
      parentRoute: typeof rootRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsImport
      parentRoute: typeof rootRoute
    }
    '/admin/investments': {
      id: '/admin/investments'
      path: '/admin/investments'
      fullPath: '/admin/investments'
      preLoaderRoute: typeof AdminInvestmentsImport
      parentRoute: typeof rootRoute
    }
    '/admin/marketplace': {
      id: '/admin/marketplace'
      path: '/admin/marketplace'
      fullPath: '/admin/marketplace'
      preLoaderRoute: typeof AdminMarketplaceImport
      parentRoute: typeof rootRoute
    }
    '/admin/nft-registry': {
      id: '/admin/nft-registry'
      path: '/admin/nft-registry'
      fullPath: '/admin/nft-registry'
      preLoaderRoute: typeof AdminNftRegistryImport
      parentRoute: typeof rootRoute
    }
    '/admin/omnichannel': {
      id: '/admin/omnichannel'
      path: '/admin/omnichannel'
      fullPath: '/admin/omnichannel'
      preLoaderRoute: typeof AdminOmnichannelImport
      parentRoute: typeof rootRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsImport
      parentRoute: typeof rootRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileImport
      parentRoute: typeof rootRoute
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/admin/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesImport
      parentRoute: typeof rootRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesImport
      parentRoute: typeof rootRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsImport
      parentRoute: typeof rootRoute
    }
    '/admin/smtp': {
      id: '/admin/smtp'
      path: '/admin/smtp'
      fullPath: '/admin/smtp'
      preLoaderRoute: typeof AdminSmtpImport
      parentRoute: typeof rootRoute
    }
    '/admin/support-monitor': {
      id: '/admin/support-monitor'
      path: '/admin/support-monitor'
      fullPath: '/admin/support-monitor'
      preLoaderRoute: typeof AdminSupportMonitorImport
      parentRoute: typeof rootRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersImport
      parentRoute: typeof rootRoute
    }
    '/admin/vbrz-token': {
      id: '/admin/vbrz-token'
      path: '/admin/vbrz-token'
      fullPath: '/admin/vbrz-token'
      preLoaderRoute: typeof AdminVbrzTokenImport
      parentRoute: typeof rootRoute
    }
    '/agency/ads': {
      id: '/agency/ads'
      path: '/agency/ads'
      fullPath: '/agency/ads'
      preLoaderRoute: typeof AgencyAdsImport
      parentRoute: typeof rootRoute
    }
    '/agency/contracts': {
      id: '/agency/contracts'
      path: '/agency/contracts'
      fullPath: '/agency/contracts'
      preLoaderRoute: typeof AgencyContractsImport
      parentRoute: typeof rootRoute
    }
    '/agency/financial': {
      id: '/agency/financial'
      path: '/agency/financial'
      fullPath: '/agency/financial'
      preLoaderRoute: typeof AgencyFinancialImport
      parentRoute: typeof rootRoute
    }
    '/agency/owners': {
      id: '/agency/owners'
      path: '/agency/owners'
      fullPath: '/agency/owners'
      preLoaderRoute: typeof AgencyOwnersImport
      parentRoute: typeof rootRoute
    }
    '/agency/settings': {
      id: '/agency/settings'
      path: '/agency/settings'
      fullPath: '/agency/settings'
      preLoaderRoute: typeof AgencySettingsImport
      parentRoute: typeof rootRoute
    }
    '/agency/setup': {
      id: '/agency/setup'
      path: '/agency/setup'
      fullPath: '/agency/setup'
      preLoaderRoute: typeof AgencySetupImport
      parentRoute: typeof rootRoute
    }
    '/agency/site': {
      id: '/agency/site'
      path: '/agency/site'
      fullPath: '/agency/site'
      preLoaderRoute: typeof AgencySiteImport
      parentRoute: typeof rootRoute
    }
    '/agency/split-calculator': {
      id: '/agency/split-calculator'
      path: '/agency/split-calculator'
      fullPath: '/agency/split-calculator'
      preLoaderRoute: typeof AgencySplitCalculatorImport
      parentRoute: typeof rootRoute
    }
    '/agency/support': {
      id: '/agency/support'
      path: '/agency/support'
      fullPath: '/agency/support'
      preLoaderRoute: typeof AgencySupportImport
      parentRoute: typeof rootRoute
    }
    '/agency/welcome': {
      id: '/agency/welcome'
      path: '/agency/welcome'
      fullPath: '/agency/welcome'
      preLoaderRoute: typeof AgencyWelcomeImport
      parentRoute: typeof rootRoute
    }
    '/assets/new': {
      id: '/assets/new'
      path: '/assets/new'
      fullPath: '/assets/new'
      preLoaderRoute: typeof AssetsNewImport
      parentRoute: typeof rootRoute
    }
    '/assets/pending': {
      id: '/assets/pending'
      path: '/assets/pending'
      fullPath: '/assets/pending'
      preLoaderRoute: typeof AssetsPendingImport
      parentRoute: typeof rootRoute
    }
    '/assets/success': {
      id: '/assets/success'
      path: '/assets/success'
      fullPath: '/assets/success'
      preLoaderRoute: typeof AssetsSuccessImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/register-superhost': {
      id: '/auth/register-superhost'
      path: '/auth/register-superhost'
      fullPath: '/auth/register-superhost'
      preLoaderRoute: typeof AuthRegisterSuperhostImport
      parentRoute: typeof rootRoute
    }
    '/garantidor/area': {
      id: '/garantidor/area'
      path: '/garantidor/area'
      fullPath: '/garantidor/area'
      preLoaderRoute: typeof GarantidorAreaImport
      parentRoute: typeof rootRoute
    }
    '/garantidor/termo': {
      id: '/garantidor/termo'
      path: '/garantidor/termo'
      fullPath: '/garantidor/termo'
      preLoaderRoute: typeof GarantidorTermoImport
      parentRoute: typeof rootRoute
    }
    '/imob/$slug': {
      id: '/imob/$slug'
      path: '/imob/$slug'
      fullPath: '/imob/$slug'
      preLoaderRoute: typeof ImobSlugImport
      parentRoute: typeof rootRoute
    }
    '/inquilino/area': {
      id: '/inquilino/area'
      path: '/inquilino/area'
      fullPath: '/inquilino/area'
      preLoaderRoute: typeof InquilinoAreaImport
      parentRoute: typeof rootRoute
    }
    '/investor/marketplace': {
      id: '/investor/marketplace'
      path: '/investor/marketplace'
      fullPath: '/investor/marketplace'
      preLoaderRoute: typeof InvestorMarketplaceImport
      parentRoute: typeof rootRoute
    }
    '/landlord/my-contracts': {
      id: '/landlord/my-contracts'
      path: '/landlord/my-contracts'
      fullPath: '/landlord/my-contracts'
      preLoaderRoute: typeof LandlordMyContractsImport
      parentRoute: typeof rootRoute
    }
    '/locador/area': {
      id: '/locador/area'
      path: '/locador/area'
      fullPath: '/locador/area'
      preLoaderRoute: typeof LocadorAreaImport
      parentRoute: typeof rootRoute
    }
    '/tenant/contract': {
      id: '/tenant/contract'
      path: '/tenant/contract'
      fullPath: '/tenant/contract'
      preLoaderRoute: typeof TenantContractImport
      parentRoute: typeof rootRoute
    }
    '/tenant/dashboard': {
      id: '/tenant/dashboard'
      path: '/tenant/dashboard'
      fullPath: '/tenant/dashboard'
      preLoaderRoute: typeof TenantDashboardImport
      parentRoute: typeof rootRoute
    }
    '/tenant/journey': {
      id: '/tenant/journey'
      path: '/tenant/journey'
      fullPath: '/tenant/journey'
      preLoaderRoute: typeof TenantJourneyImport
      parentRoute: typeof rootRoute
    }
    '/tenant/payments': {
      id: '/tenant/payments'
      path: '/tenant/payments'
      fullPath: '/tenant/payments'
      preLoaderRoute: typeof TenantPaymentsImport
      parentRoute: typeof rootRoute
    }
    '/tenant/profile': {
      id: '/tenant/profile'
      path: '/tenant/profile'
      fullPath: '/tenant/profile'
      preLoaderRoute: typeof TenantProfileImport
      parentRoute: typeof rootRoute
    }
    '/tenant/support': {
      id: '/tenant/support'
      path: '/tenant/support'
      fullPath: '/tenant/support'
      preLoaderRoute: typeof TenantSupportImport
      parentRoute: typeof rootRoute
    }
    '/agency/properties/new': {
      id: '/agency/properties/new'
      path: '/agency/properties/new'
      fullPath: '/agency/properties/new'
      preLoaderRoute: typeof AgencyPropertiesNewImport
      parentRoute: typeof rootRoute
    }
    '/agency/dashboard/': {
      id: '/agency/dashboard/'
      path: '/agency/dashboard'
      fullPath: '/agency/dashboard'
      preLoaderRoute: typeof AgencyDashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/agency/properties/': {
      id: '/agency/properties/'
      path: '/agency/properties'
      fullPath: '/agency/properties'
      preLoaderRoute: typeof AgencyPropertiesIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/assets/': {
      id: '/dashboard/assets/'
      path: '/dashboard/assets'
      fullPath: '/dashboard/assets'
      preLoaderRoute: typeof DashboardAssetsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clube-vbrz': typeof ClubeVbrzRoute
  '/garantidores': typeof GarantidoresRoute
  '/inquilinos': typeof InquilinosRoute
  '/investidor': typeof InvestidorRoute
  '/marketplace': typeof MarketplaceRoute
  '/p2p': typeof P2pRoute
  '/setup': typeof SetupRoute
  '/simulador': typeof SimuladorRoute
  '/verificar': typeof VerificarRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/cashback': typeof AdminCashbackRoute
  '/admin/changelog': typeof AdminChangelogRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/crm-live': typeof AdminCrmLiveRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dashboards-consultivas': typeof AdminDashboardsConsultivasRoute
  '/admin/defi': typeof AdminDefiRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/engage': typeof AdminEngageRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/flow-builder': typeof AdminFlowBuilderRoute
  '/admin/github': typeof AdminGithubRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/inspection': typeof AdminInspectionRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/nft-registry': typeof AdminNftRegistryRoute
  '/admin/omnichannel': typeof AdminOmnichannelRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/smtp': typeof AdminSmtpRoute
  '/admin/support-monitor': typeof AdminSupportMonitorRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vbrz-token': typeof AdminVbrzTokenRoute
  '/agency/ads': typeof AgencyAdsRoute
  '/agency/contracts': typeof AgencyContractsRoute
  '/agency/financial': typeof AgencyFinancialRoute
  '/agency/owners': typeof AgencyOwnersRoute
  '/agency/settings': typeof AgencySettingsRoute
  '/agency/setup': typeof AgencySetupRoute
  '/agency/site': typeof AgencySiteRoute
  '/agency/split-calculator': typeof AgencySplitCalculatorRoute
  '/agency/support': typeof AgencySupportRoute
  '/agency/welcome': typeof AgencyWelcomeRoute
  '/assets/new': typeof AssetsNewRoute
  '/assets/pending': typeof AssetsPendingRoute
  '/assets/success': typeof AssetsSuccessRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register-superhost': typeof AuthRegisterSuperhostRoute
  '/garantidor/area': typeof GarantidorAreaRoute
  '/garantidor/termo': typeof GarantidorTermoRoute
  '/imob/$slug': typeof ImobSlugRoute
  '/inquilino/area': typeof InquilinoAreaRoute
  '/investor/marketplace': typeof InvestorMarketplaceRoute
  '/landlord/my-contracts': typeof LandlordMyContractsRoute
  '/locador/area': typeof LocadorAreaRoute
  '/tenant/contract': typeof TenantContractRoute
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/journey': typeof TenantJourneyRoute
  '/tenant/payments': typeof TenantPaymentsRoute
  '/tenant/profile': typeof TenantProfileRoute
  '/tenant/support': typeof TenantSupportRoute
  '/agency/properties/new': typeof AgencyPropertiesNewRoute
  '/agency/dashboard': typeof AgencyDashboardIndexRoute
  '/agency/properties': typeof AgencyPropertiesIndexRoute
  '/dashboard/assets': typeof DashboardAssetsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clube-vbrz': typeof ClubeVbrzRoute
  '/garantidores': typeof GarantidoresRoute
  '/inquilinos': typeof InquilinosRoute
  '/investidor': typeof InvestidorRoute
  '/marketplace': typeof MarketplaceRoute
  '/p2p': typeof P2pRoute
  '/setup': typeof SetupRoute
  '/simulador': typeof SimuladorRoute
  '/verificar': typeof VerificarRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/cashback': typeof AdminCashbackRoute
  '/admin/changelog': typeof AdminChangelogRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/crm-live': typeof AdminCrmLiveRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dashboards-consultivas': typeof AdminDashboardsConsultivasRoute
  '/admin/defi': typeof AdminDefiRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/engage': typeof AdminEngageRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/flow-builder': typeof AdminFlowBuilderRoute
  '/admin/github': typeof AdminGithubRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/inspection': typeof AdminInspectionRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/nft-registry': typeof AdminNftRegistryRoute
  '/admin/omnichannel': typeof AdminOmnichannelRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/smtp': typeof AdminSmtpRoute
  '/admin/support-monitor': typeof AdminSupportMonitorRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vbrz-token': typeof AdminVbrzTokenRoute
  '/agency/ads': typeof AgencyAdsRoute
  '/agency/contracts': typeof AgencyContractsRoute
  '/agency/financial': typeof AgencyFinancialRoute
  '/agency/owners': typeof AgencyOwnersRoute
  '/agency/settings': typeof AgencySettingsRoute
  '/agency/setup': typeof AgencySetupRoute
  '/agency/site': typeof AgencySiteRoute
  '/agency/split-calculator': typeof AgencySplitCalculatorRoute
  '/agency/support': typeof AgencySupportRoute
  '/agency/welcome': typeof AgencyWelcomeRoute
  '/assets/new': typeof AssetsNewRoute
  '/assets/pending': typeof AssetsPendingRoute
  '/assets/success': typeof AssetsSuccessRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register-superhost': typeof AuthRegisterSuperhostRoute
  '/garantidor/area': typeof GarantidorAreaRoute
  '/garantidor/termo': typeof GarantidorTermoRoute
  '/imob/$slug': typeof ImobSlugRoute
  '/inquilino/area': typeof InquilinoAreaRoute
  '/investor/marketplace': typeof InvestorMarketplaceRoute
  '/landlord/my-contracts': typeof LandlordMyContractsRoute
  '/locador/area': typeof LocadorAreaRoute
  '/tenant/contract': typeof TenantContractRoute
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/journey': typeof TenantJourneyRoute
  '/tenant/payments': typeof TenantPaymentsRoute
  '/tenant/profile': typeof TenantProfileRoute
  '/tenant/support': typeof TenantSupportRoute
  '/agency/properties/new': typeof AgencyPropertiesNewRoute
  '/agency/dashboard': typeof AgencyDashboardIndexRoute
  '/agency/properties': typeof AgencyPropertiesIndexRoute
  '/dashboard/assets': typeof DashboardAssetsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/clube-vbrz': typeof ClubeVbrzRoute
  '/garantidores': typeof GarantidoresRoute
  '/inquilinos': typeof InquilinosRoute
  '/investidor': typeof InvestidorRoute
  '/marketplace': typeof MarketplaceRoute
  '/p2p': typeof P2pRoute
  '/setup': typeof SetupRoute
  '/simulador': typeof SimuladorRoute
  '/verificar': typeof VerificarRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/cashback': typeof AdminCashbackRoute
  '/admin/changelog': typeof AdminChangelogRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/crm-live': typeof AdminCrmLiveRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dashboards-consultivas': typeof AdminDashboardsConsultivasRoute
  '/admin/defi': typeof AdminDefiRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/engage': typeof AdminEngageRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/flow-builder': typeof AdminFlowBuilderRoute
  '/admin/github': typeof AdminGithubRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/inspection': typeof AdminInspectionRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/nft-registry': typeof AdminNftRegistryRoute
  '/admin/omnichannel': typeof AdminOmnichannelRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/smtp': typeof AdminSmtpRoute
  '/admin/support-monitor': typeof AdminSupportMonitorRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vbrz-token': typeof AdminVbrzTokenRoute
  '/agency/ads': typeof AgencyAdsRoute
  '/agency/contracts': typeof AgencyContractsRoute
  '/agency/financial': typeof AgencyFinancialRoute
  '/agency/owners': typeof AgencyOwnersRoute
  '/agency/settings': typeof AgencySettingsRoute
  '/agency/setup': typeof AgencySetupRoute
  '/agency/site': typeof AgencySiteRoute
  '/agency/split-calculator': typeof AgencySplitCalculatorRoute
  '/agency/support': typeof AgencySupportRoute
  '/agency/welcome': typeof AgencyWelcomeRoute
  '/assets/new': typeof AssetsNewRoute
  '/assets/pending': typeof AssetsPendingRoute
  '/assets/success': typeof AssetsSuccessRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register-superhost': typeof AuthRegisterSuperhostRoute
  '/garantidor/area': typeof GarantidorAreaRoute
  '/garantidor/termo': typeof GarantidorTermoRoute
  '/imob/$slug': typeof ImobSlugRoute
  '/inquilino/area': typeof InquilinoAreaRoute
  '/investor/marketplace': typeof InvestorMarketplaceRoute
  '/landlord/my-contracts': typeof LandlordMyContractsRoute
  '/locador/area': typeof LocadorAreaRoute
  '/tenant/contract': typeof TenantContractRoute
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/journey': typeof TenantJourneyRoute
  '/tenant/payments': typeof TenantPaymentsRoute
  '/tenant/profile': typeof TenantProfileRoute
  '/tenant/support': typeof TenantSupportRoute
  '/agency/properties/new': typeof AgencyPropertiesNewRoute
  '/agency/dashboard/': typeof AgencyDashboardIndexRoute
  '/agency/properties/': typeof AgencyPropertiesIndexRoute
  '/dashboard/assets/': typeof DashboardAssetsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clube-vbrz'
    | '/garantidores'
    | '/inquilinos'
    | '/investidor'
    | '/marketplace'
    | '/p2p'
    | '/setup'
    | '/simulador'
    | '/verificar'
    | '/admin/about'
    | '/admin/ads'
    | '/admin/agencies'
    | '/admin/analytics'
    | '/admin/auditoria'
    | '/admin/cashback'
    | '/admin/changelog'
    | '/admin/communication'
    | '/admin/contact'
    | '/admin/contracts'
    | '/admin/crm-live'
    | '/admin/dashboard'
    | '/admin/dashboards-consultivas'
    | '/admin/defi'
    | '/admin/docs'
    | '/admin/engage'
    | '/admin/feature-flags'
    | '/admin/financeiro'
    | '/admin/flow-builder'
    | '/admin/github'
    | '/admin/help'
    | '/admin/inspection'
    | '/admin/integrations'
    | '/admin/investments'
    | '/admin/marketplace'
    | '/admin/nft-registry'
    | '/admin/omnichannel'
    | '/admin/permissions'
    | '/admin/profile'
    | '/admin/properties'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/smtp'
    | '/admin/support-monitor'
    | '/admin/users'
    | '/admin/vbrz-token'
    | '/agency/ads'
    | '/agency/contracts'
    | '/agency/financial'
    | '/agency/owners'
    | '/agency/settings'
    | '/agency/setup'
    | '/agency/site'
    | '/agency/split-calculator'
    | '/agency/support'
    | '/agency/welcome'
    | '/assets/new'
    | '/assets/pending'
    | '/assets/success'
    | '/auth/login'
    | '/auth/register-superhost'
    | '/garantidor/area'
    | '/garantidor/termo'
    | '/imob/$slug'
    | '/inquilino/area'
    | '/investor/marketplace'
    | '/landlord/my-contracts'
    | '/locador/area'
    | '/tenant/contract'
    | '/tenant/dashboard'
    | '/tenant/journey'
    | '/tenant/payments'
    | '/tenant/profile'
    | '/tenant/support'
    | '/agency/properties/new'
    | '/agency/dashboard'
    | '/agency/properties'
    | '/dashboard/assets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clube-vbrz'
    | '/garantidores'
    | '/inquilinos'
    | '/investidor'
    | '/marketplace'
    | '/p2p'
    | '/setup'
    | '/simulador'
    | '/verificar'
    | '/admin/about'
    | '/admin/ads'
    | '/admin/agencies'
    | '/admin/analytics'
    | '/admin/auditoria'
    | '/admin/cashback'
    | '/admin/changelog'
    | '/admin/communication'
    | '/admin/contact'
    | '/admin/contracts'
    | '/admin/crm-live'
    | '/admin/dashboard'
    | '/admin/dashboards-consultivas'
    | '/admin/defi'
    | '/admin/docs'
    | '/admin/engage'
    | '/admin/feature-flags'
    | '/admin/financeiro'
    | '/admin/flow-builder'
    | '/admin/github'
    | '/admin/help'
    | '/admin/inspection'
    | '/admin/integrations'
    | '/admin/investments'
    | '/admin/marketplace'
    | '/admin/nft-registry'
    | '/admin/omnichannel'
    | '/admin/permissions'
    | '/admin/profile'
    | '/admin/properties'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/smtp'
    | '/admin/support-monitor'
    | '/admin/users'
    | '/admin/vbrz-token'
    | '/agency/ads'
    | '/agency/contracts'
    | '/agency/financial'
    | '/agency/owners'
    | '/agency/settings'
    | '/agency/setup'
    | '/agency/site'
    | '/agency/split-calculator'
    | '/agency/support'
    | '/agency/welcome'
    | '/assets/new'
    | '/assets/pending'
    | '/assets/success'
    | '/auth/login'
    | '/auth/register-superhost'
    | '/garantidor/area'
    | '/garantidor/termo'
    | '/imob/$slug'
    | '/inquilino/area'
    | '/investor/marketplace'
    | '/landlord/my-contracts'
    | '/locador/area'
    | '/tenant/contract'
    | '/tenant/dashboard'
    | '/tenant/journey'
    | '/tenant/payments'
    | '/tenant/profile'
    | '/tenant/support'
    | '/agency/properties/new'
    | '/agency/dashboard'
    | '/agency/properties'
    | '/dashboard/assets'
  id:
    | '__root__'
    | '/'
    | '/clube-vbrz'
    | '/garantidores'
    | '/inquilinos'
    | '/investidor'
    | '/marketplace'
    | '/p2p'
    | '/setup'
    | '/simulador'
    | '/verificar'
    | '/admin/about'
    | '/admin/ads'
    | '/admin/agencies'
    | '/admin/analytics'
    | '/admin/auditoria'
    | '/admin/cashback'
    | '/admin/changelog'
    | '/admin/communication'
    | '/admin/contact'
    | '/admin/contracts'
    | '/admin/crm-live'
    | '/admin/dashboard'
    | '/admin/dashboards-consultivas'
    | '/admin/defi'
    | '/admin/docs'
    | '/admin/engage'
    | '/admin/feature-flags'
    | '/admin/financeiro'
    | '/admin/flow-builder'
    | '/admin/github'
    | '/admin/help'
    | '/admin/inspection'
    | '/admin/integrations'
    | '/admin/investments'
    | '/admin/marketplace'
    | '/admin/nft-registry'
    | '/admin/omnichannel'
    | '/admin/permissions'
    | '/admin/profile'
    | '/admin/properties'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/smtp'
    | '/admin/support-monitor'
    | '/admin/users'
    | '/admin/vbrz-token'
    | '/agency/ads'
    | '/agency/contracts'
    | '/agency/financial'
    | '/agency/owners'
    | '/agency/settings'
    | '/agency/setup'
    | '/agency/site'
    | '/agency/split-calculator'
    | '/agency/support'
    | '/agency/welcome'
    | '/assets/new'
    | '/assets/pending'
    | '/assets/success'
    | '/auth/login'
    | '/auth/register-superhost'
    | '/garantidor/area'
    | '/garantidor/termo'
    | '/imob/$slug'
    | '/inquilino/area'
    | '/investor/marketplace'
    | '/landlord/my-contracts'
    | '/locador/area'
    | '/tenant/contract'
    | '/tenant/dashboard'
    | '/tenant/journey'
    | '/tenant/payments'
    | '/tenant/profile'
    | '/tenant/support'
    | '/agency/properties/new'
    | '/agency/dashboard/'
    | '/agency/properties/'
    | '/dashboard/assets/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClubeVbrzRoute: typeof ClubeVbrzRoute
  GarantidoresRoute: typeof GarantidoresRoute
  InquilinosRoute: typeof InquilinosRoute
  InvestidorRoute: typeof InvestidorRoute
  MarketplaceRoute: typeof MarketplaceRoute
  P2pRoute: typeof P2pRoute
  SetupRoute: typeof SetupRoute
  SimuladorRoute: typeof SimuladorRoute
  VerificarRoute: typeof VerificarRoute
  AdminAboutRoute: typeof AdminAboutRoute
  AdminAdsRoute: typeof AdminAdsRoute
  AdminAgenciesRoute: typeof AdminAgenciesRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminCashbackRoute: typeof AdminCashbackRoute
  AdminChangelogRoute: typeof AdminChangelogRoute
  AdminCommunicationRoute: typeof AdminCommunicationRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminContractsRoute: typeof AdminContractsRoute
  AdminCrmLiveRoute: typeof AdminCrmLiveRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDashboardsConsultivasRoute: typeof AdminDashboardsConsultivasRoute
  AdminDefiRoute: typeof AdminDefiRoute
  AdminDocsRoute: typeof AdminDocsRoute
  AdminEngageRoute: typeof AdminEngageRoute
  AdminFeatureFlagsRoute: typeof AdminFeatureFlagsRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminFlowBuilderRoute: typeof AdminFlowBuilderRoute
  AdminGithubRoute: typeof AdminGithubRoute
  AdminHelpRoute: typeof AdminHelpRoute
  AdminInspectionRoute: typeof AdminInspectionRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminInvestmentsRoute: typeof AdminInvestmentsRoute
  AdminMarketplaceRoute: typeof AdminMarketplaceRoute
  AdminNftRegistryRoute: typeof AdminNftRegistryRoute
  AdminOmnichannelRoute: typeof AdminOmnichannelRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminPropertiesRoute: typeof AdminPropertiesRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSmtpRoute: typeof AdminSmtpRoute
  AdminSupportMonitorRoute: typeof AdminSupportMonitorRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVbrzTokenRoute: typeof AdminVbrzTokenRoute
  AgencyAdsRoute: typeof AgencyAdsRoute
  AgencyContractsRoute: typeof AgencyContractsRoute
  AgencyFinancialRoute: typeof AgencyFinancialRoute
  AgencyOwnersRoute: typeof AgencyOwnersRoute
  AgencySettingsRoute: typeof AgencySettingsRoute
  AgencySetupRoute: typeof AgencySetupRoute
  AgencySiteRoute: typeof AgencySiteRoute
  AgencySplitCalculatorRoute: typeof AgencySplitCalculatorRoute
  AgencySupportRoute: typeof AgencySupportRoute
  AgencyWelcomeRoute: typeof AgencyWelcomeRoute
  AssetsNewRoute: typeof AssetsNewRoute
  AssetsPendingRoute: typeof AssetsPendingRoute
  AssetsSuccessRoute: typeof AssetsSuccessRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterSuperhostRoute: typeof AuthRegisterSuperhostRoute
  GarantidorAreaRoute: typeof GarantidorAreaRoute
  GarantidorTermoRoute: typeof GarantidorTermoRoute
  ImobSlugRoute: typeof ImobSlugRoute
  InquilinoAreaRoute: typeof InquilinoAreaRoute
  InvestorMarketplaceRoute: typeof InvestorMarketplaceRoute
  LandlordMyContractsRoute: typeof LandlordMyContractsRoute
  LocadorAreaRoute: typeof LocadorAreaRoute
  TenantContractRoute: typeof TenantContractRoute
  TenantDashboardRoute: typeof TenantDashboardRoute
  TenantJourneyRoute: typeof TenantJourneyRoute
  TenantPaymentsRoute: typeof TenantPaymentsRoute
  TenantProfileRoute: typeof TenantProfileRoute
  TenantSupportRoute: typeof TenantSupportRoute
  AgencyPropertiesNewRoute: typeof AgencyPropertiesNewRoute
  AgencyDashboardIndexRoute: typeof AgencyDashboardIndexRoute
  AgencyPropertiesIndexRoute: typeof AgencyPropertiesIndexRoute
  DashboardAssetsIndexRoute: typeof DashboardAssetsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClubeVbrzRoute: ClubeVbrzRoute,
  GarantidoresRoute: GarantidoresRoute,
  InquilinosRoute: InquilinosRoute,
  InvestidorRoute: InvestidorRoute,
  MarketplaceRoute: MarketplaceRoute,
  P2pRoute: P2pRoute,
  SetupRoute: SetupRoute,
  SimuladorRoute: SimuladorRoute,
  VerificarRoute: VerificarRoute,
  AdminAboutRoute: AdminAboutRoute,
  AdminAdsRoute: AdminAdsRoute,
  AdminAgenciesRoute: AdminAgenciesRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminCashbackRoute: AdminCashbackRoute,
  AdminChangelogRoute: AdminChangelogRoute,
  AdminCommunicationRoute: AdminCommunicationRoute,
  AdminContactRoute: AdminContactRoute,
  AdminContractsRoute: AdminContractsRoute,
  AdminCrmLiveRoute: AdminCrmLiveRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDashboardsConsultivasRoute: AdminDashboardsConsultivasRoute,
  AdminDefiRoute: AdminDefiRoute,
  AdminDocsRoute: AdminDocsRoute,
  AdminEngageRoute: AdminEngageRoute,
  AdminFeatureFlagsRoute: AdminFeatureFlagsRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminFlowBuilderRoute: AdminFlowBuilderRoute,
  AdminGithubRoute: AdminGithubRoute,
  AdminHelpRoute: AdminHelpRoute,
  AdminInspectionRoute: AdminInspectionRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminInvestmentsRoute: AdminInvestmentsRoute,
  AdminMarketplaceRoute: AdminMarketplaceRoute,
  AdminNftRegistryRoute: AdminNftRegistryRoute,
  AdminOmnichannelRoute: AdminOmnichannelRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminPropertiesRoute: AdminPropertiesRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSmtpRoute: AdminSmtpRoute,
  AdminSupportMonitorRoute: AdminSupportMonitorRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVbrzTokenRoute: AdminVbrzTokenRoute,
  AgencyAdsRoute: AgencyAdsRoute,
  AgencyContractsRoute: AgencyContractsRoute,
  AgencyFinancialRoute: AgencyFinancialRoute,
  AgencyOwnersRoute: AgencyOwnersRoute,
  AgencySettingsRoute: AgencySettingsRoute,
  AgencySetupRoute: AgencySetupRoute,
  AgencySiteRoute: AgencySiteRoute,
  AgencySplitCalculatorRoute: AgencySplitCalculatorRoute,
  AgencySupportRoute: AgencySupportRoute,
  AgencyWelcomeRoute: AgencyWelcomeRoute,
  AssetsNewRoute: AssetsNewRoute,
  AssetsPendingRoute: AssetsPendingRoute,
  AssetsSuccessRoute: AssetsSuccessRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterSuperhostRoute: AuthRegisterSuperhostRoute,
  GarantidorAreaRoute: GarantidorAreaRoute,
  GarantidorTermoRoute: GarantidorTermoRoute,
  ImobSlugRoute: ImobSlugRoute,
  InquilinoAreaRoute: InquilinoAreaRoute,
  InvestorMarketplaceRoute: InvestorMarketplaceRoute,
  LandlordMyContractsRoute: LandlordMyContractsRoute,
  LocadorAreaRoute: LocadorAreaRoute,
  TenantContractRoute: TenantContractRoute,
  TenantDashboardRoute: TenantDashboardRoute,
  TenantJourneyRoute: TenantJourneyRoute,
  TenantPaymentsRoute: TenantPaymentsRoute,
  TenantProfileRoute: TenantProfileRoute,
  TenantSupportRoute: TenantSupportRoute,
  AgencyPropertiesNewRoute: AgencyPropertiesNewRoute,
  AgencyDashboardIndexRoute: AgencyDashboardIndexRoute,
  AgencyPropertiesIndexRoute: AgencyPropertiesIndexRoute,
  DashboardAssetsIndexRoute: DashboardAssetsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/clube-vbrz",
        "/garantidores",
        "/inquilinos",
        "/investidor",
        "/marketplace",
        "/p2p",
        "/setup",
        "/simulador",
        "/verificar",
        "/admin/about",
        "/admin/ads",
        "/admin/agencies",
        "/admin/analytics",
        "/admin/auditoria",
        "/admin/cashback",
        "/admin/changelog",
        "/admin/communication",
        "/admin/contact",
        "/admin/contracts",
        "/admin/crm-live",
        "/admin/dashboard",
        "/admin/dashboards-consultivas",
        "/admin/defi",
        "/admin/docs",
        "/admin/engage",
        "/admin/feature-flags",
        "/admin/financeiro",
        "/admin/flow-builder",
        "/admin/github",
        "/admin/help",
        "/admin/inspection",
        "/admin/integrations",
        "/admin/investments",
        "/admin/marketplace",
        "/admin/nft-registry",
        "/admin/omnichannel",
        "/admin/permissions",
        "/admin/profile",
        "/admin/properties",
        "/admin/roles",
        "/admin/settings",
        "/admin/smtp",
        "/admin/support-monitor",
        "/admin/users",
        "/admin/vbrz-token",
        "/agency/ads",
        "/agency/contracts",
        "/agency/financial",
        "/agency/owners",
        "/agency/settings",
        "/agency/setup",
        "/agency/site",
        "/agency/split-calculator",
        "/agency/support",
        "/agency/welcome",
        "/assets/new",
        "/assets/pending",
        "/assets/success",
        "/auth/login",
        "/auth/register-superhost",
        "/garantidor/area",
        "/garantidor/termo",
        "/imob/$slug",
        "/inquilino/area",
        "/investor/marketplace",
        "/landlord/my-contracts",
        "/locador/area",
        "/tenant/contract",
        "/tenant/dashboard",
        "/tenant/journey",
        "/tenant/payments",
        "/tenant/profile",
        "/tenant/support",
        "/agency/properties/new",
        "/agency/dashboard/",
        "/agency/properties/",
        "/dashboard/assets/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/clube-vbrz": {
      "filePath": "clube-vbrz.tsx"
    },
    "/garantidores": {
      "filePath": "garantidores.tsx"
    },
    "/inquilinos": {
      "filePath": "inquilinos.tsx"
    },
    "/investidor": {
      "filePath": "investidor.tsx"
    },
    "/marketplace": {
      "filePath": "marketplace.tsx"
    },
    "/p2p": {
      "filePath": "p2p.tsx"
    },
    "/setup": {
      "filePath": "setup.tsx"
    },
    "/simulador": {
      "filePath": "simulador.tsx"
    },
    "/verificar": {
      "filePath": "verificar.tsx"
    },
    "/admin/about": {
      "filePath": "admin/about.tsx"
    },
    "/admin/ads": {
      "filePath": "admin/ads.tsx"
    },
    "/admin/agencies": {
      "filePath": "admin/agencies.tsx"
    },
    "/admin/analytics": {
      "filePath": "admin/analytics.tsx"
    },
    "/admin/auditoria": {
      "filePath": "admin/auditoria.tsx"
    },
    "/admin/cashback": {
      "filePath": "admin/cashback.tsx"
    },
    "/admin/changelog": {
      "filePath": "admin/changelog.tsx"
    },
    "/admin/communication": {
      "filePath": "admin/communication.tsx"
    },
    "/admin/contact": {
      "filePath": "admin/contact.tsx"
    },
    "/admin/contracts": {
      "filePath": "admin/contracts.tsx"
    },
    "/admin/crm-live": {
      "filePath": "admin/crm-live.tsx"
    },
    "/admin/dashboard": {
      "filePath": "admin/dashboard.tsx"
    },
    "/admin/dashboards-consultivas": {
      "filePath": "admin/dashboards-consultivas.tsx"
    },
    "/admin/defi": {
      "filePath": "admin/defi.tsx"
    },
    "/admin/docs": {
      "filePath": "admin/docs.tsx"
    },
    "/admin/engage": {
      "filePath": "admin/engage.tsx"
    },
    "/admin/feature-flags": {
      "filePath": "admin/feature-flags.tsx"
    },
    "/admin/financeiro": {
      "filePath": "admin/financeiro.tsx"
    },
    "/admin/flow-builder": {
      "filePath": "admin/flow-builder.tsx"
    },
    "/admin/github": {
      "filePath": "admin/github.tsx"
    },
    "/admin/help": {
      "filePath": "admin/help.tsx"
    },
    "/admin/inspection": {
      "filePath": "admin/inspection.tsx"
    },
    "/admin/integrations": {
      "filePath": "admin/integrations.tsx"
    },
    "/admin/investments": {
      "filePath": "admin/investments.tsx"
    },
    "/admin/marketplace": {
      "filePath": "admin/marketplace.tsx"
    },
    "/admin/nft-registry": {
      "filePath": "admin/nft-registry.tsx"
    },
    "/admin/omnichannel": {
      "filePath": "admin/omnichannel.tsx"
    },
    "/admin/permissions": {
      "filePath": "admin/permissions.tsx"
    },
    "/admin/profile": {
      "filePath": "admin/profile.tsx"
    },
    "/admin/properties": {
      "filePath": "admin/properties.tsx"
    },
    "/admin/roles": {
      "filePath": "admin/roles.tsx"
    },
    "/admin/settings": {
      "filePath": "admin/settings.tsx"
    },
    "/admin/smtp": {
      "filePath": "admin/smtp.tsx"
    },
    "/admin/support-monitor": {
      "filePath": "admin/support-monitor.tsx"
    },
    "/admin/users": {
      "filePath": "admin/users.tsx"
    },
    "/admin/vbrz-token": {
      "filePath": "admin/vbrz-token.tsx"
    },
    "/agency/ads": {
      "filePath": "agency/ads.tsx"
    },
    "/agency/contracts": {
      "filePath": "agency/contracts.tsx"
    },
    "/agency/financial": {
      "filePath": "agency/financial.tsx"
    },
    "/agency/owners": {
      "filePath": "agency/owners.tsx"
    },
    "/agency/settings": {
      "filePath": "agency/settings.tsx"
    },
    "/agency/setup": {
      "filePath": "agency/setup.tsx"
    },
    "/agency/site": {
      "filePath": "agency/site.tsx"
    },
    "/agency/split-calculator": {
      "filePath": "agency/split-calculator.tsx"
    },
    "/agency/support": {
      "filePath": "agency/support.tsx"
    },
    "/agency/welcome": {
      "filePath": "agency/welcome.tsx"
    },
    "/assets/new": {
      "filePath": "assets/new.tsx"
    },
    "/assets/pending": {
      "filePath": "assets/pending.tsx"
    },
    "/assets/success": {
      "filePath": "assets/success.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/register-superhost": {
      "filePath": "auth/register-superhost.tsx"
    },
    "/garantidor/area": {
      "filePath": "garantidor/area.tsx"
    },
    "/garantidor/termo": {
      "filePath": "garantidor/termo.tsx"
    },
    "/imob/$slug": {
      "filePath": "imob/$slug.tsx"
    },
    "/inquilino/area": {
      "filePath": "inquilino/area.tsx"
    },
    "/investor/marketplace": {
      "filePath": "investor/marketplace.tsx"
    },
    "/landlord/my-contracts": {
      "filePath": "landlord/my-contracts.tsx"
    },
    "/locador/area": {
      "filePath": "locador/area.tsx"
    },
    "/tenant/contract": {
      "filePath": "tenant/contract.tsx"
    },
    "/tenant/dashboard": {
      "filePath": "tenant/dashboard.tsx"
    },
    "/tenant/journey": {
      "filePath": "tenant/journey.tsx"
    },
    "/tenant/payments": {
      "filePath": "tenant/payments.tsx"
    },
    "/tenant/profile": {
      "filePath": "tenant/profile.tsx"
    },
    "/tenant/support": {
      "filePath": "tenant/support.tsx"
    },
    "/agency/properties/new": {
      "filePath": "agency/properties/new.tsx"
    },
    "/agency/dashboard/": {
      "filePath": "agency/dashboard/index.tsx"
    },
    "/agency/properties/": {
      "filePath": "agency/properties/index.tsx"
    },
    "/dashboard/assets/": {
      "filePath": "dashboard/assets/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
